### ISSUE TITLE
great job!

### ISSUE THREAD

**Issue by dixinyinli2** [yoshall/Awesome-Trajectory-Computing#1]
You guys are doing a great job! Is your Google Cloud Drive for trajectory datasets ready? hahaha

**Comment by Onedean** [comment]
> You guys are doing a great job! Is your Google Cloud Drive for trajectory datasets ready? hahaha

Hi, dixinyinli2

Thank you for your interest in our work! If this helps with your work, that's great.🫡 However, we can't distribute most datasets due to copyright issues, which is unfortunate.😫 But we've provided links to access datasets for each one in the table. We hope this helps with your problem.😉

Cheers,
Wei
